export const ROLES = {
  SUPER_ADMIN: 101,
  ADMIN: 102,
  CUSTOMER: 103,
  EMPLOYEE: 104
};
export const PERMISSIONS = {
  CAN_MANAGE_ADMINS: 1000,
  CAN_MANAGE_EMPLOYEES: 1001,
  CAN_ACCESS_REPORTS: 1002,
  CAN_UPDATE_PRODUCTS: 1003,
  CAN_MODIFY_USERS: 1004,
  CAN_LOG_REQUEST: 1005,
  CAN_ADD_ADMINS: 1006,
  CAN_ADD_CUSTOMER: 1007,
  CAN_ADD_EMPLOYEE: 1008,
  CAN_VIEW_PAYMENTS: 1009
};

export const getPermissions = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.CAN_ACCESS_REPORTS,
    PERMISSIONS.CAN_MANAGE_ADMINS,
    PERMISSIONS.CAN_ADD_ADMINS,
    PERMISSIONS.CAN_MANAGE_EMPLOYEES
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.CAN_VIEW_PAYMENTS,
    PERMISSIONS.CAN_MANAGE_EMPLOYEES,
    PERMISSIONS.CAN_ADD_EMPLOYEE
  ],
  [ROLES.CUSTOMER]: [PERMISSIONS.CAN_LOG_REQUEST],
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.CAN_UPDATE_PRODUCTS,
    PERMISSIONS.CAN_LOG_REQUEST,
    PERMISSIONS.CAN_MODIFY_USERS
  ]
};
